name: Dodoi´s Renhold AS
favicon: null
layout_spectrum: 0.24805353279225528
typography_spectrum: 0.67388
title: Dodoi`s
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.905521884560585
  lightness: 0.7226862753741443
  saturation: 0.6289619018789381
  rhythmicContrast: 0.04188445373438299
purpose: []
